import type { ContentPage } from "./types";

export const platforms: ContentPage[] = [
  {
    slug: "framer-agency",
    h1: "Framer Agency",
    metaTitle: "Framer Agency — Certified Framer Experts | Devowise",
    metaDescription: "Certified Framer agency shipping production Framer sites with CMS, motion, and code overrides. Trusted by SaaS, AI, and creative brands.",
    eyebrow: "Framer Agency",
    heroTitle: "A certified Framer agency, not a template shop.",
    heroSub: "We ship production Framer sites, real CMS, real motion, real code, for teams that expect a bespoke result.",
    overview: [
      "Framer is the fastest way to ship a beautiful, interactive site, but only in the hands of a team that understands its edges. As a certified Framer agency we combine design, motion, and code overrides to build sites templates can't touch.",
      "Every engagement is principal-led and covers positioning, design, CMS, and launch. No account managers, no offshoring.",
    ],
    benefits: [
      { title: "Certified experts", desc: "Recognized by Framer as top-tier practitioners." },
      { title: "Design + build in one tool", desc: "No handoff drift, faster iterations." },
      { title: "Motion as a discipline", desc: "Interactions with taste, not just spring physics." },
      { title: "Code where it counts", desc: "Custom React components and overrides on demand." },
    ],
    process: [
      { step: "01", title: "Kickoff", desc: "Positioning, content plan, CMS model." },
      { step: "02", title: "Design", desc: "High-fidelity design directly in Framer." },
      { step: "03", title: "Build", desc: "Components, CMS, code overrides, integrations." },
      { step: "04", title: "Launch", desc: "SEO, analytics, and post-launch iteration." },
    ],
    features: [
      "Framer certified team",
      "CMS collections & localization",
      "Code overrides in React",
      "Motion & Lottie system",
      "SEO & structured data",
      "Post-launch retainer available",
    ],
    industries: ["SaaS", "AI Startups", "Creative Agencies", "Coaches & Consultants"],
    faqs: [
      { q: "Why choose Framer over Webflow?", a: "Framer wins on motion, iteration speed, and design fidelity. Webflow wins on CMS depth and enterprise governance." },
      { q: "Can Framer power a large marketing site?", a: "Yes, 50+ page CMS-driven Framer sites are our normal." },
      { q: "Do you offer training?", a: "Yes, we can hand off a Framer project with editor training and documentation." },
    ],
    related: {
      services: ["framer-development", "website-design", "landing-page-design"],
      resources: ["framer-vs-webflow"],
    },
  },
  {
    slug: "webflow-agency",
    h1: "Webflow Agency",
    metaTitle: "Webflow Agency — Expert Webflow Development | Devowise",
    metaDescription: "Webflow agency building content-rich, multi-language, and e-commerce sites. Bespoke design, structured CMS, and clean custom code.",
    eyebrow: "Webflow Agency",
    heroTitle: "A Webflow agency for teams that will outgrow their site.",
    heroSub: "Content models, custom code, and integrations engineered so your Webflow site scales as your business does.",
    overview: [
      "Webflow is our platform of choice for content-heavy, multi-language, and e-commerce sites that need enterprise-grade governance without an enterprise CMS budget.",
      "We design content models before designing screens, so the CMS reflects how your team actually publishes, not how a theme thinks you should.",
    ],
    benefits: [
      { title: "Structured CMS", desc: "Collections and references designed around real editorial." },
      { title: "Enterprise-ready", desc: "Roles, workflows, and governance that scale." },
      { title: "Custom code", desc: "JS, integrations, and attributes without breaking the editor." },
      { title: "Localization", desc: "Weglot or Webflow Localization done properly." },
    ],
    process: [
      { step: "01", title: "Model", desc: "CMS schema and IA." },
      { step: "02", title: "Design", desc: "Bespoke design and component library." },
      { step: "03", title: "Build", desc: "Templates, integrations, custom code." },
      { step: "04", title: "Launch", desc: "SEO, redirects, editor training, go-live." },
    ],
    features: [
      "Webflow CMS & Ecommerce",
      "Localization (Weglot / native)",
      "Custom JS & API integrations",
      "Editor training and SOPs",
      "SEO & schema baked in",
      "Ongoing retainer available",
    ],
    industries: ["SaaS", "E-commerce", "Education", "Marketing Agencies"],
    faqs: [
      { q: "Can you migrate from WordPress?", a: "Yes, including redirects, SEO parity, and content mapping." },
      { q: "Do you build Webflow Ecommerce?", a: "Yes, for smaller catalogs. For large or subscription commerce we recommend Shopify." },
      { q: "Do you offer retainers?", a: "Yes, monthly retainers for iteration, CRO, and new pages." },
    ],
    related: {
      services: ["webflow-development", "shopify-development", "website-development"],
      resources: ["framer-vs-webflow"],
    },
  },
  {
    slug: "shopify-agency",
    h1: "Shopify Agency",
    metaTitle: "Shopify Agency — Themes, Hydrogen, and CRO | Devowise",
    metaDescription: "Shopify Partner agency building custom themes, headless Hydrogen storefronts, and CRO programs for premium DTC and B2B brands.",
    eyebrow: "Shopify Agency",
    heroTitle: "A Shopify agency that treats margin as a design constraint.",
    heroSub: "Custom themes, Hydrogen, and CRO, engineered so conversion, LTV, and operational sanity all go up.",
    overview: [
      "As a Shopify Partner, we build stores for brands that treat design and speed as competitive advantages, not vanity.",
      "From bespoke Liquid themes to Hydrogen storefronts, we design for the funnel first: PDPs, cart, checkout, and post-purchase flows tuned against your actual data.",
    ],
    benefits: [
      { title: "Conversion-tuned", desc: "PDPs and cart designed against real funnel data." },
      { title: "Fast on mobile", desc: "Themes engineered for LCP under 2s." },
      { title: "Merchandising flexibility", desc: "Section-based theming for campaigns." },
      { title: "Headless when it earns its keep", desc: "Hydrogen and Storefront API on demand." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Funnel, checkout, analytics baseline." },
      { step: "02", title: "Design", desc: "PLP, PDP, cart, and campaign templates." },
      { step: "03", title: "Build", desc: "Custom Liquid or Hydrogen storefront." },
      { step: "04", title: "Grow", desc: "Ongoing CRO and campaign work." },
    ],
    features: [
      "Shopify Partner",
      "Custom Liquid themes",
      "Hydrogen headless",
      "Klaviyo & subscription apps",
      "Checkout customization (Plus)",
      "CRO retainer available",
    ],
    industries: ["Fashion", "Beauty", "DTC", "B2B Commerce"],
    faqs: [
      { q: "Do we need Shopify Plus?", a: "Only for checkout customization and enterprise multi-store. We help you evaluate." },
      { q: "WooCommerce migration?", a: "Yes, catalog, orders, redirects, and SEO. See our Shopify vs WooCommerce guide." },
      { q: "Do you handle apps?", a: "Yes, we integrate or custom-build (Klaviyo, subscriptions, reviews, loyalty)." },
    ],
    related: {
      services: ["shopify-development", "conversion-rate-optimisation"],
      resources: ["shopify-vs-woocommerce"],
      industries: ["ecommerce"],
    },
  },
  {
    slug: "kajabi-experts",
    h1: "Kajabi Experts",
    metaTitle: "Kajabi Experts — Certified Kajabi Design & Development | Devowise",
    metaDescription: "Certified Kajabi experts building custom themes, sales funnels, and member portals that lift enrollments and retention.",
    eyebrow: "Kajabi Experts",
    heroTitle: "Certified Kajabi experts, offer to portal to renewal.",
    heroSub: "Custom Kajabi themes and funnels for coaches, creators, and educators who want to look like the category leader.",
    overview: [
      "Kajabi is a full growth stack, and default themes make every course look the same. As certified Kajabi experts we design bespoke themes, sales funnels, and member portals that stand apart.",
      "We treat offer, funnel, checkout, and portal as one experience, then instrument the whole thing so you know exactly what's converting.",
    ],
    benefits: [
      { title: "Bespoke, not templated", desc: "Custom themes that feel like your brand." },
      { title: "Full funnel", desc: "Sales pages, upsells, and order bumps wired end-to-end." },
      { title: "Member experience", desc: "Portals designed for engagement, not just enrollment." },
      { title: "Certified expertise", desc: "Recognized by Kajabi as top-tier practitioners." },
    ],
    process: [
      { step: "01", title: "Offer", desc: "Positioning, pricing, and funnel structure." },
      { step: "02", title: "Design", desc: "Theme, sales page, and portal design." },
      { step: "03", title: "Build", desc: "Theme dev, automations, community." },
      { step: "04", title: "Optimise", desc: "CRO, retention, expansion." },
    ],
    features: [
      "Certified Kajabi expertise",
      "Custom Kajabi themes",
      "Sales & upsell funnels",
      "Community and portal design",
      "Email automations",
      "Analytics & CRO setup",
    ],
    industries: ["Coaches", "Consultants", "Creators", "Educators"],
    faqs: [
      { q: "Do you migrate from Teachable/Thinkific?", a: "Yes, content, students, and email lists included." },
      { q: "Can Kajabi handle a large community?", a: "Yes, we've shipped Kajabi builds serving thousands of members." },
      { q: "Do you write copy?", a: "We collaborate with a specialist or work from your existing copy." },
    ],
    related: {
      services: ["kajabi-development", "landing-page-design"],
      industries: ["coaches-consultants", "education"],
    },
  },
  {
    slug: "wordpress-development",
    h1: "WordPress Development",
    metaTitle: "WordPress Development — Custom Themes & Headless | Devowise",
    metaDescription: "WordPress development done right: custom themes, ACF-driven layouts, and headless WordPress with Next.js. Fast, secure, and maintainable.",
    eyebrow: "WordPress",
    heroTitle: "WordPress, but built like modern software.",
    heroSub: "Custom themes, ACF-driven layouts, and headless WordPress with Next.js, when the business case demands it.",
    overview: [
      "We build WordPress when a client has a real reason to stay on it: existing content team, plugin ecosystem, or a headless setup that pairs with Next.js.",
      "Every build ships with a custom theme, block or ACF architecture your editors love, and a performance baseline WordPress isn't famous for.",
    ],
    benefits: [
      { title: "Custom, not themed", desc: "No page-builder bloat, no theme spaghetti." },
      { title: "Editor-friendly", desc: "ACF or Gutenberg blocks designed around your content." },
      { title: "Fast", desc: "Aggressive caching, image pipelines, Core Web Vitals green." },
      { title: "Headless-ready", desc: "Next.js or Astro frontend when it earns its keep." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Content, plugins, and performance baseline." },
      { step: "02", title: "Design", desc: "Bespoke design and block library." },
      { step: "03", title: "Build", desc: "Custom theme or headless build." },
      { step: "04", title: "Launch", desc: "Redirects, caching, SEO, and go-live." },
    ],
    features: [
      "Custom WordPress themes",
      "ACF / Gutenberg blocks",
      "Headless with Next.js / Astro",
      "WooCommerce integration",
      "Performance & security hardening",
      "Editor training",
    ],
    industries: ["Publishers", "Education", "Non-profits", "Enterprise"],
    faqs: [
      { q: "Should we move off WordPress?", a: "Sometimes. If your team is small and content simple, Webflow or Framer might be a better fit." },
      { q: "Do you do headless WordPress?", a: "Yes, WPGraphQL + Next.js is a stack we ship regularly." },
      { q: "WooCommerce or Shopify?", a: "Shopify for growth-stage DTC. WooCommerce when you need deep WordPress integration." },
    ],
    related: {
      services: ["website-development", "website-redesign"],
    },
  },
  {
    slug: "figma-design",
    h1: "Figma Design",
    metaTitle: "Figma Design Services — Systems, Prototypes, and Handoff | Devowise",
    metaDescription: "Figma design services: bespoke UI, design systems, interactive prototypes, and dev handoff engineered for production teams.",
    eyebrow: "Figma",
    heroTitle: "Figma files your engineers actually want to build from.",
    heroSub: "Bespoke UI, design systems, and interactive prototypes structured for real production teams.",
    overview: [
      "Every Figma file we ship is production-oriented: named layers, variants, auto-layout, tokens, and dev-mode-ready specs. No 'final-v3-copy.fig' handoffs.",
      "We build design systems that survive scale, and prototypes that let your team validate before spending engineering weeks.",
    ],
    benefits: [
      { title: "Production-ready files", desc: "Variants, tokens, and auto-layout by default." },
      { title: "Design systems that scale", desc: "Library architecture that outlasts a rebrand." },
      { title: "Interactive prototypes", desc: "Enough fidelity to validate with real users." },
      { title: "Dev handoff without friction", desc: "Dev-mode specs, tokens JSON, and QA support." },
    ],
    process: [
      { step: "01", title: "Foundations", desc: "Tokens, type, color, and grid setup." },
      { step: "02", title: "Components", desc: "Variants, states, and documentation." },
      { step: "03", title: "Screens", desc: "Bespoke UI built from the system." },
      { step: "04", title: "Handoff", desc: "Prototype, dev-mode, and engineering QA." },
    ],
    features: [
      "Design tokens (JSON export)",
      "Component library with variants",
      "Interactive prototypes",
      "Dev-mode annotations",
      "Accessibility considerations",
      "Living style guide",
    ],
    industries: ["SaaS", "AI Startups", "Fintech", "Enterprise"],
    faqs: [
      { q: "Can you extend our existing design system?", a: "Yes, audit first, then refactor or extend." },
      { q: "Do you support Storybook sync?", a: "Yes, we can pair a Figma library with a Storybook implementation." },
      { q: "Do you build too?", a: "Yes, our engineers implement the same files." },
    ],
    related: {
      services: ["ui-ux-design", "brand-identity-design", "website-development"],
    },
  },
];