import type { ContentPage } from "./types";

export const resources: ContentPage[] = [
  {
    slug: "framer-vs-webflow",
    h1: "Framer vs Webflow: An Honest Comparison",
    metaTitle: "Framer vs Webflow (2026) — Which Should You Pick? | Devowise",
    metaDescription: "Framer vs Webflow: an honest 2026 comparison across motion, CMS, e-commerce, localization, and dev overrides, from a team that ships both.",
    eyebrow: "Comparison",
    heroTitle: "Framer vs Webflow, from a team that ships both.",
    heroSub: "A pragmatic comparison across motion, CMS, e-commerce, localization, and developer overrides, so you can pick the right tool for the job.",
    overview: [
      "We build production sites on both Framer and Webflow every week, so this isn't a fanboy piece. Both platforms are excellent, and both are wrong for certain projects.",
      "The short version: Framer wins on motion, iteration speed, and design fidelity. Webflow wins on CMS depth, enterprise governance, and multi-language complexity.",
    ],
    benefits: [
      { title: "Framer wins for", desc: "Motion-heavy marketing sites, rapid iteration, design-first teams." },
      { title: "Webflow wins for", desc: "Structured CMS, complex localization, e-commerce, and enterprise governance." },
      { title: "Both are great for", desc: "Non-devs shipping without templates." },
      { title: "Neither is right for", desc: "Deep product apps (use React/Next) or huge catalogs (use Shopify)." },
    ],
    process: [
      { step: "01", title: "Motion", desc: "Framer wins clearly, native spring physics, scroll, and prototyping." },
      { step: "02", title: "CMS", desc: "Webflow wins, references, workflows, and roles are more mature." },
      { step: "03", title: "E-commerce", desc: "Webflow has native Ecommerce, Framer does not." },
      { step: "04", title: "Dev overrides", desc: "Framer allows real React components; Webflow ships JS attributes." },
    ],
    features: [
      "Motion capability",
      "CMS depth",
      "Localization",
      "E-commerce",
      "Developer overrides",
      "Team collaboration",
    ],
    faqs: [
      { q: "Can I migrate later?", a: "Yes, but plan for content model rework. Neither exports to the other cleanly." },
      { q: "Which is faster to launch?", a: "Framer, marginally, especially for design-led teams." },
      { q: "Which is cheaper long-term?", a: "Depends on plan. For CMS-heavy, Webflow. For simple, Framer." },
    ],
    related: {
      services: ["framer-development", "webflow-development"],
      platforms: ["framer-agency", "webflow-agency"],
    },
  },
  {
    slug: "shopify-vs-woocommerce",
    h1: "Shopify vs WooCommerce: Which Should You Choose?",
    metaTitle: "Shopify vs WooCommerce (2026) — Full Comparison | Devowise",
    metaDescription: "Shopify vs WooCommerce compared across cost, scale, checkout, apps, and international commerce, from an agency that ships both.",
    eyebrow: "Comparison",
    heroTitle: "Shopify vs WooCommerce: pick the platform that fits your margin, not the trend.",
    heroSub: "A structured comparison across cost, scale, checkout, apps, internationalization, and headless readiness.",
    overview: [
      "Both platforms can power a serious e-commerce business. Which one is right depends on your catalog size, checkout requirements, and how much engineering capacity you have on hand.",
      "The short version: Shopify wins on speed to launch, checkout security, and app ecosystem. WooCommerce wins on total flexibility if you already have WordPress and dev capacity.",
    ],
    benefits: [
      { title: "Shopify wins for", desc: "Speed to launch, checkout depth, app ecosystem, mobile speed." },
      { title: "WooCommerce wins for", desc: "Deep WordPress integration, no per-transaction fees, full flexibility." },
      { title: "Total cost", desc: "Shopify is predictable; WooCommerce is cheaper upfront, higher long-term ops." },
      { title: "Headless", desc: "Shopify Hydrogen is mature; WooCommerce headless via WPGraphQL." },
    ],
    process: [
      { step: "01", title: "Checkout", desc: "Shopify's checkout is best-in-class and hard to beat." },
      { step: "02", title: "Apps", desc: "Shopify's ecosystem is bigger and higher quality." },
      { step: "03", title: "International", desc: "Shopify Markets is easier; WooCommerce needs plugins." },
      { step: "04", title: "Flexibility", desc: "WooCommerce wins if you need total control." },
    ],
    features: [
      "Total cost of ownership",
      "Checkout customization",
      "App ecosystem",
      "International commerce",
      "Headless readiness",
      "Team maintenance burden",
    ],
    faqs: [
      { q: "Can I migrate WooCommerce to Shopify?", a: "Yes, catalog, orders, customers, redirects, and SEO. We do this monthly." },
      { q: "Shopify Plus vs regular?", a: "Plus for checkout customization, scripts, and multi-store. Otherwise regular." },
      { q: "Headless required?", a: "No, but Hydrogen is worth it for bespoke storefronts at scale." },
    ],
    related: {
      services: ["shopify-development"],
      platforms: ["shopify-agency"],
    },
  },
  {
    slug: "website-cost-guide",
    h1: "Website Cost Guide 2026",
    metaTitle: "Website Cost Guide (2026) — What a Real Site Costs | Devowise",
    metaDescription: "A realistic 2026 website cost guide across templates, agencies, and bespoke builds. What drives price, and what you actually get for it.",
    eyebrow: "Guide",
    heroTitle: "What a real website actually costs in 2026.",
    heroSub: "An honest breakdown of pricing across templates, freelancers, agencies, and bespoke builds, and what drives the number up or down.",
    overview: [
      "'How much does a website cost?' is the wrong question. The right question is: what does this site need to do for the business? Pricing follows from there.",
      "This guide breaks down realistic 2026 pricing across five common site types, plus the hidden costs most quotes leave out.",
    ],
    benefits: [
      { title: "Template ($0–2k)", desc: "DIY or freelancer on a theme. Fine for the first year, hits a wall fast." },
      { title: "Freelancer bespoke ($3–10k)", desc: "One designer/developer. Quality varies wildly." },
      { title: "Small agency ($10–40k)", desc: "Bespoke design, custom build, some strategy. The sweet spot for most startups." },
      { title: "Full agency ($40–150k+)", desc: "Full brand + product + CRO + custom engineering." },
    ],
    process: [
      { step: "01", title: "Strategy", desc: "Positioning, IA, and content plan (10–20% of budget)." },
      { step: "02", title: "Design", desc: "Bespoke UI and system (30–40%)." },
      { step: "03", title: "Build", desc: "Development and CMS (30–40%)." },
      { step: "04", title: "Launch & iterate", desc: "SEO, analytics, and post-launch (10–20%)." },
    ],
    features: [
      "Discovery and positioning",
      "Design system and bespoke UI",
      "CMS and integrations",
      "SEO and structured data",
      "Performance and accessibility",
      "Post-launch iteration",
    ],
    faqs: [
      { q: "Why the huge range?", a: "Scope. A 5-page marketing site vs a 100-page multi-language platform are different projects." },
      { q: "Hidden costs?", a: "Content writing, photography, licensing, third-party subscriptions, and ongoing hosting." },
      { q: "Fixed vs T&M?", a: "We prefer fixed scope for bounded projects, T&M for retainers." },
    ],
    related: {
      services: ["website-design", "website-development", "website-redesign"],
    },
  },
  {
    slug: "branding-checklist",
    h1: "Branding Checklist: Everything a Real Brand Needs",
    metaTitle: "Branding Checklist — What a Complete Brand System Includes | Devowise",
    metaDescription: "A complete branding checklist: strategy, identity, voice, applied templates, and governance, everything a real brand system should include.",
    eyebrow: "Checklist",
    heroTitle: "The branding checklist we use on every engagement.",
    heroSub: "Strategy through applied templates, this is the complete list of deliverables a real brand system should include.",
    overview: [
      "Most brand engagements ship a logo and call it done. A real brand system is bigger and this checklist is what we deliver every time.",
    ],
    benefits: [
      { title: "Strategy", desc: "Positioning, audience, narrative, tone of voice." },
      { title: "Identity", desc: "Logo system, type, color, motion, iconography." },
      { title: "Applied", desc: "Site, deck, social, email, print templates." },
      { title: "Governance", desc: "Guidelines PDF + Figma library + tokens." },
    ],
    process: [
      { step: "01", title: "Strategy", desc: "Research, positioning, narrative, voice." },
      { step: "02", title: "Identity", desc: "Logo, type, color, motion." },
      { step: "03", title: "Applied", desc: "Site, deck, social, email, print." },
      { step: "04", title: "Governance", desc: "Guidelines, library, tokens." },
    ],
    features: [
      "Positioning doc",
      "Voice & tone guide",
      "Logo lockup system",
      "Type & color tokens",
      "Motion principles",
      "Applied templates & guidelines",
    ],
    faqs: [
      { q: "How long does a full brand engagement take?", a: "4–8 weeks depending on scope." },
      { q: "What if we already have a logo?", a: "We build the rest of the system around it." },
      { q: "Do we need everything?", a: "No, we scope to what the business actually needs now." },
    ],
    related: {
      services: ["branding-services", "brand-identity-design", "logo-design"],
    },
  },
  {
    slug: "website-launch-checklist",
    h1: "Website Launch Checklist",
    metaTitle: "Website Launch Checklist — Every Step Before You Go Live | Devowise",
    metaDescription: "The website launch checklist we use on every project: SEO, analytics, performance, accessibility, and post-launch monitoring.",
    eyebrow: "Checklist",
    heroTitle: "Every step we run through before pushing a site live.",
    heroSub: "SEO, analytics, performance, accessibility, and post-launch monitoring, the complete list.",
    overview: [
      "Launch day is where most sites break. We run this checklist on every project so we don't blow up SEO, analytics, or performance the second we push.",
    ],
    benefits: [
      { title: "SEO parity", desc: "Redirects, schema, meta, sitemap, robots." },
      { title: "Analytics continuity", desc: "GA4, GTM, and events audited." },
      { title: "Performance passing", desc: "Core Web Vitals green pre-launch." },
      { title: "Accessibility", desc: "WCAG 2.2 AA baseline verified." },
    ],
    process: [
      { step: "01", title: "Pre-launch", desc: "SEO, analytics, redirect map." },
      { step: "02", title: "Content", desc: "Copy, meta, images optimized." },
      { step: "03", title: "Launch", desc: "DNS, redirects, monitoring on." },
      { step: "04", title: "Post-launch", desc: "Week-1 SEO watch, event QA." },
    ],
    features: [
      "Redirect map",
      "SEO meta and schema",
      "Analytics and event audit",
      "Performance budget",
      "Accessibility check",
      "Post-launch monitoring",
    ],
    faqs: [
      { q: "How long does launch take?", a: "Usually 1–2 days including QA and monitoring." },
      { q: "Can we phase launch?", a: "Yes, by section or template to reduce risk." },
      { q: "What if something breaks?", a: "We monitor and roll back or hotfix within hours." },
    ],
    related: {
      services: ["website-development", "website-redesign", "seo-services"],
    },
  },
  {
    slug: "ux-best-practices",
    h1: "UX Best Practices for Product Teams",
    metaTitle: "UX Best Practices — Principles That Ship | Devowise",
    metaDescription: "UX best practices for product teams: information architecture, interaction, motion, and accessibility, principles we apply on every build.",
    eyebrow: "Best Practices",
    heroTitle: "UX principles we apply on every product build.",
    heroSub: "Information architecture, interaction, motion, and accessibility, distilled into practical rules our team ships against.",
    overview: [
      "Most 'UX best practice' lists read like undergraduate homework. This one is drawn from what we've shipped, and what we've had to fix in production.",
    ],
    benefits: [
      { title: "IA first", desc: "Fix structure before pixels." },
      { title: "One primary action", desc: "Every screen has one obvious next step." },
      { title: "Motion earns its keep", desc: "Guide the eye, don't decorate." },
      { title: "Accessibility from day one", desc: "WCAG 2.2 AA is a floor, not a stretch." },
    ],
    process: [
      { step: "01", title: "IA", desc: "Structure content around user jobs." },
      { step: "02", title: "Interaction", desc: "Predictable patterns beat clever ones." },
      { step: "03", title: "Motion", desc: "Use it to teach, not to impress." },
      { step: "04", title: "Accessibility", desc: "Test with real assistive tech." },
    ],
    features: [
      "Job-based IA",
      "Single primary action per screen",
      "Predictable interaction patterns",
      "Motion for state, not decoration",
      "Real-user testing",
      "Accessibility baseline",
    ],
    faqs: [
      { q: "Do you follow specific frameworks?", a: "We use JTBD and heuristics, but stay tool-agnostic." },
      { q: "How do you test?", a: "Prototype in Figma, moderated user tests, session replay in production." },
      { q: "How much research per project?", a: "As little as needed to answer the question, as much as needed to be right." },
    ],
    related: {
      services: ["ui-ux-design", "website-design"],
    },
  },
  {
    slug: "website-seo-checklist",
    h1: "Website SEO Checklist",
    metaTitle: "Website SEO Checklist — Technical + On-Page Fundamentals | Devowise",
    metaDescription: "A practical website SEO checklist: technical fundamentals, on-page, structured data, and topical authority basics, applied by a shipping team.",
    eyebrow: "Checklist",
    heroTitle: "The SEO checklist we run on every site we build.",
    heroSub: "Technical fundamentals, on-page, structured data, and topical authority basics, all in one list.",
    overview: [
      "SEO doesn't have to be mystical. Ship the fundamentals well and you outrank most of your competitors on effort alone. This is the list we work through every launch.",
    ],
    benefits: [
      { title: "Technical", desc: "Crawlability, indexation, Core Web Vitals, schema." },
      { title: "On-page", desc: "Unique titles, descriptions, headings, and copy." },
      { title: "Structured data", desc: "Organization, Article, Product, FAQ, Breadcrumb where relevant." },
      { title: "Topical authority", desc: "Pillar + cluster structure with real internal linking." },
    ],
    process: [
      { step: "01", title: "Technical", desc: "Sitemap, robots, canonical, schema, Vitals." },
      { step: "02", title: "On-page", desc: "Titles, meta, headings, copy uniqueness." },
      { step: "03", title: "Content", desc: "Pillar + cluster + internal linking." },
      { step: "04", title: "Monitor", desc: "GSC, rankings, Vitals in production." },
    ],
    features: [
      "XML sitemap",
      "Robots.txt",
      "Canonical URLs",
      "Schema.org structured data",
      "Core Web Vitals passing",
      "Internal linking system",
    ],
    faqs: [
      { q: "How long until we rank?", a: "Technical wins land in weeks, content takes 3–9 months to compound." },
      { q: "Do you write content?", a: "We handle briefs and structure; writing can be us, your team, or a specialist." },
      { q: "Link building?", a: "Content + digital PR, not paid schemes." },
    ],
    related: {
      services: ["seo-services", "website-development"],
    },
  },
];