import type { ContentPage } from "./types";

export const services: ContentPage[] = [
  {
    slug: "branding-services",
    h1: "Branding Services",
    metaTitle: "Branding Services — Strategy, Identity & Systems | Devowise",
    metaDescription: "End-to-end branding services: positioning, naming, visual identity, voice, and scalable brand systems for AI, SaaS, and product-led companies.",
    eyebrow: "Branding",
    heroTitle: "Branding built to compound in value, not just look good on a deck.",
    heroSub: "We design brands as operating systems, positioning, voice, identity, and applied guidelines your team can actually use.",
    overview: [
      "Devowise builds brands for companies that treat design as leverage. Strategy first, aesthetic second, so every color, mark, and word ladders back to how you win.",
      "We work end-to-end from customer research and messaging through visual identity, motion, and applied templates, delivered as a living brand system your team can ship against for years.",
    ],
    benefits: [
      { title: "Positioning that closes deals", desc: "Sharpened messaging that helps your pitch, deck, and site convert." },
      { title: "Identity that scales", desc: "A visual system engineered for product, marketing, and social from day one." },
      { title: "Consistency across surfaces", desc: "Tokens, templates, and guidelines your team applies without a designer." },
      { title: "Faster launches", desc: "Reusable components mean weeks off every future campaign." },
    ],
    process: [
      { step: "01", title: "Research", desc: "Stakeholder interviews, competitor teardown, category mapping." },
      { step: "02", title: "Positioning", desc: "Narrative, tone of voice, and audience articulation." },
      { step: "03", title: "Identity", desc: "Logo, type, color, motion, and brand components." },
      { step: "04", title: "System", desc: "Guidelines, templates, and asset library shipped in Figma." },
    ],
    features: [
      "Brand strategy & positioning",
      "Naming & narrative",
      "Full visual identity system",
      "Motion & sonic guidelines",
      "Deck, pitch, and social templates",
      "Applied brand guidelines (PDF + Figma)",
    ],
    industries: ["SaaS", "AI Startups", "Fintech", "E-commerce", "Healthcare"],
    faqs: [
      { q: "How long does a full branding engagement take?", a: "Typically 4–8 weeks depending on scope, from research through applied guidelines." },
      { q: "Do you handle naming?", a: "Yes, including trademark screening, domain checks, and category-fit testing." },
      { q: "Can you rebrand without downtime?", a: "We phase the rollout site, product, marketing, so nothing breaks and the brand lands consistently." },
    ],
    related: {
      services: ["brand-identity-design", "logo-design", "website-design"],
      industries: ["saas", "ai-startups"],
      solutions: ["build-brand-scratch"],
    },
  },
  {
    slug: "brand-identity-design",
    h1: "Brand Identity Design",
    metaTitle: "Brand Identity Design — Logo, Type, Color & Motion | Devowise",
    metaDescription: "Complete brand identity design: logo, type system, color, motion, and reusable components delivered as a production-ready Figma system.",
    eyebrow: "Brand Identity",
    heroTitle: "A brand identity that feels intentional in every pixel.",
    heroSub: "Marks, type, color, and motion designed as one coherent system, not a Pinterest board dressed up as guidelines.",
    overview: [
      "We design identity systems that work at 16px in a favicon and 40ft on a booth wall. Every component is engineered against real product and marketing use cases before it ships.",
      "The final deliverable is a Figma library your designers, marketers, and engineers pull from directly, plus a PDF guideline your leadership can actually flip through.",
    ],
    benefits: [
      { title: "Distinctive & defensible", desc: "Marks that stand out in category and stay ownable long-term." },
      { title: "Production-ready", desc: "Every asset shipped in the formats your teams need on day one." },
      { title: "Systemized", desc: "Tokens for color, type, and space, ready to sync into code." },
      { title: "Extensible", desc: "Room to grow into sub-brands, products, and campaigns." },
    ],
    process: [
      { step: "01", title: "Explore", desc: "3–4 divergent identity directions rooted in your positioning." },
      { step: "02", title: "Refine", desc: "Compress to one direction and push it across real surfaces." },
      { step: "03", title: "System", desc: "Codify type, color, grid, motion, and components." },
      { step: "04", title: "Ship", desc: "Deliver Figma library, PDF, and applied templates." },
    ],
    features: [
      "Primary + responsive logo lockups",
      "Type system (display, body, mono)",
      "Color tokens (light + dark)",
      "Iconography direction",
      "Motion principles & Lottie source",
      "Brand components in Figma",
    ],
    industries: ["SaaS", "AI Startups", "E-commerce", "Fintech"],
    faqs: [
      { q: "How many logo directions do you show?", a: "Usually three, each grounded in a different strategic angle, not just visual variety." },
      { q: "Do you deliver design tokens?", a: "Yes, exported as JSON so your engineers can import them into Tailwind, CSS, or a design token pipeline." },
      { q: "What if we already have a logo?", a: "We can build a full identity around an existing mark or refine it as part of the system." },
    ],
    related: {
      services: ["branding-services", "logo-design", "ui-ux-design"],
      solutions: ["build-brand-scratch"],
    },
  },
  {
    slug: "logo-design",
    h1: "Logo Design",
    metaTitle: "Logo Design Services — Marks Built to Last | Devowise",
    metaDescription: "Custom logo design for startups and established brands: distinctive, responsive, and delivered as a full mark system, not a single PNG.",
    eyebrow: "Logo",
    heroTitle: "Logos designed as marks, not decorations.",
    heroSub: "We treat the logo as the first component of a brand system, drawn for real product and marketing constraints from the first sketch.",
    overview: [
      "A logo has to work at 16px in a browser tab, in a favicon, embossed on a card, and animated in your intro sequence. Ours are drawn with those constraints in mind from day one.",
      "You get a full lockup system, primary, responsive, mono, and reversed, along with clear usage rules and source files in every format your team will actually use.",
    ],
    benefits: [
      { title: "Ownable & timeless", desc: "Marks screened for category, culture, and trademark viability." },
      { title: "Responsive by design", desc: "Reads at every size, from favicon to billboard." },
      { title: "System, not sticker", desc: "Primary, secondary, monogram, and app icon variants included." },
      { title: "Every format", desc: "SVG, PNG, PDF, plus favicon and social kit." },
    ],
    process: [
      { step: "01", title: "Brief", desc: "Positioning, audience, and category audit." },
      { step: "02", title: "Sketch", desc: "3 divergent conceptual routes." },
      { step: "03", title: "Refine", desc: "One direction, drawn to production quality." },
      { step: "04", title: "Deliver", desc: "Full lockup system + usage guidelines." },
    ],
    features: [
      "3 conceptual directions",
      "Primary + responsive lockups",
      "Monogram / favicon variant",
      "Color and mono versions",
      "Clear-space and misuse guidelines",
      "Source files (SVG, AI, Figma)",
    ],
    industries: ["Startups", "SaaS", "E-commerce", "Consulting"],
    faqs: [
      { q: "How many rounds of revisions?", a: "Two full rounds after direction selection, plus polish. Most brands land inside that scope." },
      { q: "Do you do trademark screening?", a: "We do a first-pass conflict check; formal trademark filing is done through your counsel." },
      { q: "Turnaround?", a: "Typically 2–3 weeks for a full lockup system." },
    ],
    related: { services: ["brand-identity-design", "branding-services"] },
  },
  {
    slug: "ui-ux-design",
    h1: "UI/UX Design",
    metaTitle: "UI/UX Design Services — Product-Led Interfaces | Devowise",
    metaDescription: "Product UX and UI design that ships. Research, IA, interaction, and pixel-perfect UI built as reusable design systems in Figma.",
    eyebrow: "UI/UX",
    heroTitle: "Interfaces engineered around real product jobs.",
    heroSub: "We design product experiences the way we build them, systematically, from information architecture through motion and micro-interactions.",
    overview: [
      "UI/UX at Devowise means more than pretty screens. We map jobs to be done, prototype critical flows, and stress-test them before a single component is polished.",
      "The final design system is a Figma library your engineers can implement one-to-one, with tokens, variants, and states already covered.",
    ],
    benefits: [
      { title: "Higher activation", desc: "Onboarding designed to move users to value fast." },
      { title: "Fewer redesigns", desc: "IA and states figured out before UI, not after launch." },
      { title: "Faster dev handoff", desc: "Design system + Figma variants means zero guesswork." },
      { title: "Motion where it earns its keep", desc: "Micro-interactions that guide, not decorate." },
    ],
    process: [
      { step: "01", title: "Research", desc: "User interviews, analytics review, competitor teardown." },
      { step: "02", title: "Flows", desc: "Information architecture and low-fidelity wireframes." },
      { step: "03", title: "UI", desc: "High-fidelity screens with a full component library." },
      { step: "04", title: "Handoff", desc: "Tokens, specs, prototype, engineering QA." },
    ],
    features: [
      "User research & personas",
      "Information architecture",
      "Interaction & motion design",
      "Full component library in Figma",
      "Design tokens (JSON)",
      "Prototype + engineering QA",
    ],
    industries: ["SaaS", "AI Startups", "Fintech", "Healthcare"],
    faqs: [
      { q: "Do you cover mobile as well as web?", a: "Yes, iOS, Android, and responsive web share the same underlying system." },
      { q: "Can you work with our existing design system?", a: "We can extend, refactor, or wrap it, depending on where it's held together with tape." },
      { q: "How do you handle engineering handoff?", a: "We work directly with your engineers, share Figma dev mode, and QA the built output." },
    ],
    related: {
      services: ["website-design", "website-development", "landing-page-design"],
      industries: ["saas", "ai-startups"],
    },
  },
  {
    slug: "website-design",
    h1: "Website Design",
    metaTitle: "Website Design Services — High-Conversion & On-Brand | Devowise",
    metaDescription: "Bespoke website design for product, marketing, and content-heavy sites. Editorial layouts, motion, and reusable systems that convert.",
    eyebrow: "Website Design",
    heroTitle: "Websites designed to sell the product, not the design.",
    heroSub: "Custom website design that balances editorial polish with commercial intent, and hands off cleanly into any dev stack.",
    overview: [
      "Every site we design starts with a positioning workshop and a conversion audit. Layout, hierarchy, and content decisions ladder back to a single job: turn attention into pipeline.",
      "The output is a full page system, not a stack of PNGs. Reusable sections, states, and content variations that let you launch new campaigns without another design sprint.",
    ],
    benefits: [
      { title: "Conversion-first hierarchy", desc: "Every section earns its place against a measurable job." },
      { title: "Editorial polish", desc: "Layouts, type, and motion that feel like a magazine, not a template." },
      { title: "Reusable page system", desc: "Sections your team can recompose without a designer." },
      { title: "Dev-ready", desc: "Shipped in Figma with tokens, variants, and a build brief." },
    ],
    process: [
      { step: "01", title: "Positioning", desc: "Message architecture and content plan." },
      { step: "02", title: "Wireframe", desc: "Low-fidelity page structures reviewed against goals." },
      { step: "03", title: "Design", desc: "High-fidelity layouts, motion, and a section library." },
      { step: "04", title: "Handoff", desc: "Figma library + build brief for Framer, Webflow, or code." },
    ],
    features: [
      "Content and message architecture",
      "5–15 page bespoke design",
      "Reusable section library",
      "Motion & interaction spec",
      "Responsive breakpoints in Figma",
      "CMS content model",
    ],
    industries: ["SaaS", "AI Startups", "Real Estate", "E-commerce"],
    faqs: [
      { q: "Do you also build the site?", a: "Yes, in Framer, Webflow, Shopify, or custom code, or hand off cleanly to your team." },
      { q: "How many pages are included?", a: "Most engagements cover 5–15 unique templates plus a section library for endless variations." },
      { q: "What if we need a redesign, not a new site?", a: "See our website redesign service, same rigor, different starting point." },
    ],
    related: {
      services: ["website-development", "framer-development", "webflow-development", "landing-page-design"],
      solutions: ["modern-website-design", "website-redesign"],
    },
  },
  {
    slug: "website-development",
    h1: "Website Development",
    metaTitle: "Website Development — Fast, SEO-Ready, Scalable | Devowise",
    metaDescription: "Custom website development in Next.js, TanStack, Framer, or Webflow. Fast, accessible, SEO-ready, and easy for your team to own.",
    eyebrow: "Development",
    heroTitle: "Websites built once, scaled cleanly for years.",
    heroSub: "We ship sites that are fast, accessible, and structured, so SEO, growth, and product teams don't fight the codebase later.",
    overview: [
      "Whether it's Next.js, TanStack Start, Framer, or Webflow, we pick the stack your business will thrive in, not the one that's trendy this quarter.",
      "Every build ships with clean semantic HTML, Core Web Vitals in the green, structured data, and a CMS your team can operate without a developer on-call.",
    ],
    benefits: [
      { title: "Fast by default", desc: "Core Web Vitals passing, real-user monitored." },
      { title: "SEO-ready", desc: "Semantic HTML, schema, sitemap, and OG images from launch." },
      { title: "Editable by your team", desc: "CMS models designed around how you actually publish." },
      { title: "Scales with product", desc: "Design system in code, ready to grow into an app surface." },
    ],
    process: [
      { step: "01", title: "Scoping", desc: "Stack, CMS, hosting, and integrations decided against goals." },
      { step: "02", title: "Foundations", desc: "Design system, tokens, CI, and analytics wired in." },
      { step: "03", title: "Build", desc: "Pages and templates built in vertical slices." },
      { step: "04", title: "Launch", desc: "QA, performance pass, SEO audit, and go-live." },
    ],
    features: [
      "Next.js, TanStack, Framer or Webflow",
      "Headless CMS integration",
      "Design system in code",
      "Structured data & OG images",
      "Performance budget & monitoring",
      "Analytics & experimentation setup",
    ],
    industries: ["SaaS", "AI Startups", "E-commerce", "Marketing Agencies"],
    faqs: [
      { q: "Which CMS do you recommend?", a: "It depends. Sanity, Contentful, Prismic, or the platform-native CMS for Framer, Webflow, and Shopify." },
      { q: "Can you migrate from WordPress?", a: "Yes, including redirects, SEO parity, and content mapping." },
      { q: "Do you handle hosting?", a: "We deploy to Vercel, Cloudflare, or your own infra and hand off documentation." },
    ],
    related: {
      services: ["website-design", "framer-development", "webflow-development", "website-maintenance"],
      solutions: ["slow-website-optimisation", "modern-website-design"],
    },
  },
  {
    slug: "framer-development",
    h1: "Framer Development",
    metaTitle: "Framer Development — Certified Framer Experts | Devowise",
    metaDescription: "Certified Framer development for marketing sites, product pages, and CMS-driven experiences. Motion, CMS, and clean code overrides.",
    eyebrow: "Framer",
    heroTitle: "Framer sites built by certified experts, not template flippers.",
    heroSub: "Custom Framer builds with rich motion, real CMS structures, and code overrides where the visual editor stops being enough.",
    overview: [
      "Framer is our default choice when a team wants editorial freedom, fast iteration, and elite motion without giving up performance. As certified Framer experts, we build production sites, not decorated demos.",
      "Every project ships with a proper CMS model, reusable component variants, localization where needed, and code overrides for the interactions Framer's UI can't express.",
    ],
    benefits: [
      { title: "Design + build in one tool", desc: "Faster iteration and no design-to-code drift." },
      { title: "Elite motion", desc: "Scroll, spring, and physics animations built into the platform." },
      { title: "CMS for content teams", desc: "Structured collections your marketers own." },
      { title: "Code where it matters", desc: "Overrides and custom components for anything the UI can't do." },
    ],
    process: [
      { step: "01", title: "Design", desc: "Layouts and motion designed inside Framer for zero handoff loss." },
      { step: "02", title: "System", desc: "Reusable components, variants, and tokens." },
      { step: "03", title: "CMS", desc: "Collections for blog, case studies, products, or docs." },
      { step: "04", title: "Launch", desc: "SEO, forms, integrations, analytics, and go-live." },
    ],
    features: [
      "Certified Framer expertise",
      "Design + build in Framer",
      "CMS collections & localization",
      "Advanced motion & Lottie",
      "Code overrides & custom components",
      "Analytics, forms, and CRM integrations",
    ],
    industries: ["SaaS", "AI Startups", "Creative Agencies", "Startups"],
    faqs: [
      { q: "Can Framer handle a large marketing site?", a: "Yes, we ship 50+ page CMS-driven sites in Framer regularly." },
      { q: "Framer vs Webflow, which should we pick?", a: "See our Framer vs Webflow guide, short answer: it depends on team, motion, and CMS complexity." },
      { q: "Do you build custom Framer components?", a: "Yes, in React, delivered as reusable code components." },
    ],
    related: {
      services: ["webflow-development", "website-design", "landing-page-design"],
      platforms: ["framer-agency"],
      resources: ["framer-vs-webflow"],
    },
  },
  {
    slug: "webflow-development",
    h1: "Webflow Development",
    metaTitle: "Webflow Development — Enterprise-Grade Webflow Sites | Devowise",
    metaDescription: "Webflow development for content-heavy, multi-language, and e-commerce sites. Clean CMS models, custom code, and integrations that scale.",
    eyebrow: "Webflow",
    heroTitle: "Webflow sites that hold up as your content grows.",
    heroSub: "Structured CMS, custom code, and integrations, engineered so your marketing team can ship without breaking anything.",
    overview: [
      "Webflow is our choice when a team needs a rock-solid CMS, complex localization, or deep e-commerce, delivered with the polish of a bespoke site.",
      "We design content models first, so collections, references, and templates match how you actually publish, not how a template thinks you should.",
    ],
    benefits: [
      { title: "Structured CMS", desc: "Collections, references, and workflows designed around real editorial needs." },
      { title: "Multi-language ready", desc: "Native localization with Weglot or Webflow Localization." },
      { title: "Custom code where needed", desc: "Attributes, custom JS, and API integrations without breaking the editor." },
      { title: "Client-friendly editor", desc: "Structured components your team can update safely." },
    ],
    process: [
      { step: "01", title: "Model", desc: "CMS schema and page templates mapped to editorial workflow." },
      { step: "02", title: "Build", desc: "Style system, components, and templates in Webflow." },
      { step: "03", title: "Integrate", desc: "Forms, CRM, analytics, and third-party APIs." },
      { step: "04", title: "Launch", desc: "SEO, redirects, performance pass, and go-live." },
    ],
    features: [
      "Webflow CMS & Ecommerce",
      "Localization (Weglot / native)",
      "Custom JS & API integrations",
      "Design system in Webflow classes",
      "Editor training for your team",
      "Ongoing maintenance available",
    ],
    industries: ["SaaS", "E-commerce", "Marketing Agencies", "Education"],
    faqs: [
      { q: "Can you handle a WordPress-to-Webflow migration?", a: "Yes, including redirects, SEO parity, and CMS content mapping." },
      { q: "Webflow Ecommerce or Shopify?", a: "Depends on catalog size, checkout complexity, and internationalization needs, we'll advise." },
      { q: "Do you offer Webflow retainers?", a: "Yes, monthly retainers for iteration, CRO, and new page rollouts." },
    ],
    related: {
      services: ["framer-development", "shopify-development", "website-development"],
      platforms: ["webflow-agency"],
      resources: ["framer-vs-webflow"],
    },
  },
  {
    slug: "shopify-development",
    h1: "Shopify Development",
    metaTitle: "Shopify Development — Custom Themes & Storefronts | Devowise",
    metaDescription: "Custom Shopify development for premium DTC and B2B brands. Custom themes, headless storefronts, Liquid, Hydrogen, and app integrations.",
    eyebrow: "Shopify",
    heroTitle: "Shopify storefronts built for margin, not just traffic.",
    heroSub: "Custom themes, Liquid, headless Hydrogen, and app integrations, tuned for conversion, LTV, and operational sanity.",
    overview: [
      "As a Shopify Partner, we build storefronts that treat conversion, load time, and merchandising as first-class problems, not afterthoughts.",
      "Whether you're launching, replatforming, or going headless with Hydrogen, we design a system your team can operate, extend, and A/B test without waiting on us.",
    ],
    benefits: [
      { title: "Conversion-tuned", desc: "PDPs, cart, and checkout designed against real DTC funnels." },
      { title: "Fast on real devices", desc: "Themes engineered for LCP under 2s on mid-range mobile." },
      { title: "Merchandising flexibility", desc: "Section-based theming your team can recompose per campaign." },
      { title: "Headless-ready", desc: "Hydrogen and Storefront API when a bespoke stack is worth the lift." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Analytics, checkout, and CRO baseline." },
      { step: "02", title: "Design", desc: "PLP, PDP, cart, and campaign templates." },
      { step: "03", title: "Build", desc: "Custom Liquid theme or Hydrogen storefront." },
      { step: "04", title: "Launch", desc: "App integrations, testing, and go-live." },
    ],
    features: [
      "Custom Liquid themes",
      "Hydrogen / headless storefronts",
      "Checkout customization (Plus)",
      "Subscription & bundle apps",
      "Klaviyo & CRM integrations",
      "CRO & experimentation setup",
    ],
    industries: ["E-commerce", "Fashion", "Beauty", "DTC"],
    faqs: [
      { q: "Do we need Shopify Plus?", a: "Only if you need checkout customization, scripts, or advanced multi-store. We help you evaluate." },
      { q: "Can you migrate from WooCommerce?", a: "Yes, catalog, orders, redirects, and SEO. See our Shopify vs WooCommerce guide." },
      { q: "Do you handle post-launch?", a: "Yes, retainers for CRO, seasonal campaigns, and new features." },
    ],
    related: {
      services: ["webflow-development", "website-development", "conversion-rate-optimisation"],
      platforms: ["shopify-agency"],
      resources: ["shopify-vs-woocommerce"],
    },
  },
  {
    slug: "kajabi-development",
    h1: "Kajabi Development",
    metaTitle: "Kajabi Development — Certified Kajabi Experts | Devowise",
    metaDescription: "Certified Kajabi experts building high-conversion course, coaching, and membership sites with custom themes and funnels.",
    eyebrow: "Kajabi",
    heroTitle: "Kajabi sites that actually sell your product.",
    heroSub: "Certified Kajabi experts building custom themes, funnels, and communities that move visitors to paid faster.",
    overview: [
      "Kajabi is powerful, and hard to make feel bespoke. As certified Kajabi experts we build custom themes and funnels that don't look like every other course landing page.",
      "We design the offer, the sales page, the checkout, and the member portal as one connected experience, then instrument it so you know what's converting.",
    ],
    benefits: [
      { title: "Bespoke, not templated", desc: "Custom themes that look and feel like your brand." },
      { title: "Funnels that convert", desc: "Sales pages, order bumps, and upsells wired end-to-end." },
      { title: "Member experience", desc: "Portals designed to keep learners engaged, not just enrolled." },
      { title: "Analytics you can act on", desc: "Funnel tracking that ties campaigns to revenue." },
    ],
    process: [
      { step: "01", title: "Offer", desc: "Clarify positioning, pricing, and funnel structure." },
      { step: "02", title: "Design", desc: "Custom theme, sales page, and portal design." },
      { step: "03", title: "Build", desc: "Theme dev, checkout, automations, community." },
      { step: "04", title: "Optimise", desc: "Post-launch CRO, retention, and expansion." },
    ],
    features: [
      "Certified Kajabi expertise",
      "Custom Kajabi themes",
      "Sales & upsell funnels",
      "Community and portal design",
      "Email automations",
      "Analytics & CRO setup",
    ],
    industries: ["Coaches", "Consultants", "Education", "Creators"],
    faqs: [
      { q: "Do you migrate from Teachable or Thinkific?", a: "Yes, including content, students, and email lists." },
      { q: "Can Kajabi handle a large community?", a: "Yes, we've shipped Kajabi builds serving thousands of active members." },
      { q: "Do you write sales copy?", a: "We collaborate with a specialist copywriter or work from your existing copy." },
    ],
    related: {
      services: ["website-design", "landing-page-design", "conversion-rate-optimisation"],
      platforms: ["kajabi-experts"],
      industries: ["coaches-consultants"],
    },
  },
  {
    slug: "landing-page-design",
    h1: "Landing Page Design",
    metaTitle: "Landing Page Design — High-Conversion Pages | Devowise",
    metaDescription: "Landing page design and build for product launches, campaigns, and paid traffic. Message-tested, motion-rich, and CRO-ready.",
    eyebrow: "Landing Pages",
    heroTitle: "Landing pages engineered to convert cold traffic.",
    heroSub: "Message-first, motion-tuned landing pages built to make the offer irresistible and the CTA impossible to miss.",
    overview: [
      "Landing pages are the sharpest test of message-market fit. We start with a message doc, iterate against your best-performing ads, then design and build the page as a system, not a static image.",
      "You get a page you can A/B test, personalize by traffic source, and evolve without a redesign every quarter.",
    ],
    benefits: [
      { title: "Message-first design", desc: "Copy and hierarchy tested before pixel decisions." },
      { title: "Motion with intent", desc: "Micro-interactions that carry the eye to the CTA." },
      { title: "Built for A/B", desc: "Section variants ready for experimentation." },
      { title: "Fast, everywhere", desc: "Sub-2s LCP on mid-range mobile devices." },
    ],
    process: [
      { step: "01", title: "Message", desc: "Offer, audience, and objection map." },
      { step: "02", title: "Design", desc: "Hero, proof, offer, and CTA sections designed as a story." },
      { step: "03", title: "Build", desc: "Framer, Webflow, or Next.js implementation." },
      { step: "04", title: "Test", desc: "Analytics, heatmaps, and A/B rollout." },
    ],
    features: [
      "Message architecture doc",
      "Fully bespoke design",
      "Motion & interaction spec",
      "Framer / Webflow / Next.js build",
      "A/B ready section variants",
      "Analytics & heatmap setup",
    ],
    industries: ["SaaS", "AI Startups", "E-commerce", "Coaches & Consultants"],
    faqs: [
      { q: "How fast can you ship a landing page?", a: "Simple launches in 5–7 days. Fully bespoke pages in 2–3 weeks." },
      { q: "Do you run the A/B tests?", a: "Yes, on a retainer, or we set up your tooling so your team can run them." },
      { q: "Can we get multiple variants for paid traffic?", a: "Absolutely, that's usually part of the scope." },
    ],
    related: {
      services: ["website-design", "conversion-rate-optimisation", "framer-development"],
      solutions: ["website-not-converting", "improve-conversion"],
    },
  },
  {
    slug: "website-redesign",
    h1: "Website Redesign",
    metaTitle: "Website Redesign Services — Revamp Without SEO Loss | Devowise",
    metaDescription: "Website redesign services that preserve SEO, migrate content safely, and lift conversion. From audit to launch, done right.",
    eyebrow: "Redesign",
    heroTitle: "A redesign your SEO and conversion team will both thank you for.",
    heroSub: "We rebuild sites without losing rankings, breaking analytics, or degrading conversion, and usually improve all three.",
    overview: [
      "Most redesigns fail on rollout day: rankings drop, analytics breaks, and the new site converts worse than the one it replaced. We treat every redesign as a migration project first, redesign second.",
      "That means SEO audits, redirect plans, and content parity are scoped from day one, with new design and CRO layered on top, not bolted on.",
    ],
    benefits: [
      { title: "SEO preserved", desc: "301 map, schema parity, and content-model migration." },
      { title: "Analytics continuity", desc: "GA4, GTM, and conversion events audited and re-wired." },
      { title: "Conversion uplift", desc: "New IA and hierarchy targeted at your top-3 metrics." },
      { title: "Modern stack", desc: "Move off WordPress, Wix, or legacy code to a maintainable platform." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "SEO, analytics, and conversion baseline." },
      { step: "02", title: "Plan", desc: "Redirect map, content model, IA, and design brief." },
      { step: "03", title: "Build", desc: "New design and build in parallel with migration prep." },
      { step: "04", title: "Launch", desc: "Redirects live, monitoring on, week-1 SEO watch." },
    ],
    features: [
      "Technical SEO audit",
      "Redirect & schema map",
      "Content model & migration",
      "Bespoke redesign",
      "Framer / Webflow / Next.js build",
      "Post-launch monitoring",
    ],
    industries: ["SaaS", "E-commerce", "Real Estate", "Law Firms"],
    faqs: [
      { q: "Will our rankings drop?", a: "Not if the migration is done right. We plan redirects and content parity so search equity carries over." },
      { q: "How long does a redesign take?", a: "Typically 6–12 weeks depending on scope and content volume." },
      { q: "Can we phase the launch?", a: "Yes, we can roll out by section or template to reduce risk." },
    ],
    related: {
      services: ["website-design", "website-development", "seo-services"],
      solutions: ["website-not-converting", "slow-website-optimisation", "modern-website-design"],
    },
  },
  {
    slug: "website-maintenance",
    h1: "Website Maintenance",
    metaTitle: "Website Maintenance & Support — Monthly Retainers | Devowise",
    metaDescription: "Ongoing website maintenance, monitoring, and iteration retainers. Stay fast, secure, and always shipping improvements.",
    eyebrow: "Maintenance",
    heroTitle: "A team on standby so your site keeps compounding.",
    heroSub: "Monthly retainers for updates, monitoring, iteration, and CRO, so your site keeps getting better after launch.",
    overview: [
      "Most sites peak on launch day and slowly rot. Ours don't, because we retain a small senior team to iterate, monitor, and ship on a fixed cadence.",
      "Retainers cover everything from bug fixes and performance tuning to new sections, CMS work, and quarterly CRO sprints.",
    ],
    benefits: [
      { title: "Always shipping", desc: "New sections, campaigns, and CRO tests every month." },
      { title: "Uptime & security", desc: "Monitoring, updates, and incident response covered." },
      { title: "Performance protected", desc: "Core Web Vitals watched and defended against regressions." },
      { title: "One senior team", desc: "No new onboarding every quarter." },
    ],
    process: [
      { step: "01", title: "Kickoff", desc: "Backlog, priorities, and metrics agreed." },
      { step: "02", title: "Cadence", desc: "Weekly async standup, biweekly demo." },
      { step: "03", title: "Ship", desc: "Fixes, features, and experiments rolled out." },
      { step: "04", title: "Report", desc: "Monthly metrics, wins, and next-quarter plan." },
    ],
    features: [
      "Backlog & priorities in Linear",
      "Bug fixes & performance tuning",
      "New sections and pages",
      "CMS work and content ops",
      "A/B tests and CRO sprints",
      "Uptime, security & monitoring",
    ],
    industries: ["SaaS", "E-commerce", "Marketing Agencies", "Coaches & Consultants"],
    faqs: [
      { q: "What's the minimum commitment?", a: "3-month minimum, then month-to-month with 30 days notice." },
      { q: "Which platforms do you support?", a: "Framer, Webflow, Shopify, Kajabi, WordPress, and custom Next.js / TanStack builds." },
      { q: "Can we scale hours up or down?", a: "Yes, we resize the retainer quarterly based on your roadmap." },
    ],
    related: {
      services: ["seo-services", "conversion-rate-optimisation", "website-development"],
    },
  },
  {
    slug: "seo-services",
    h1: "SEO Services",
    metaTitle: "SEO Services — Technical, Content, and Topical Authority | Devowise",
    metaDescription: "SEO services for product-led companies: technical SEO, on-page, content strategy, and topical authority builds that compound over time.",
    eyebrow: "SEO",
    heroTitle: "SEO that compounds, not campaigns that spike and fade.",
    heroSub: "Technical foundations, topical authority, and on-page work engineered as a system, not a checklist.",
    overview: [
      "We approach SEO the way we approach product: as a system with inputs and outputs. Technical foundations, information architecture, and topical authority are the levers, ranking and pipeline are the outcomes.",
      "Every engagement starts with a full audit and a topic map. We then execute page builds, internal linking, and content in-house or with your team.",
    ],
    benefits: [
      { title: "Compounding growth", desc: "Topical authority builds that outrank one-off content." },
      { title: "Technical health", desc: "Core Web Vitals, schema, crawlability, and indexation solved." },
      { title: "Product-led content", desc: "Pages that rank AND convert, not just attract." },
      { title: "Clear reporting", desc: "Monthly wins, losses, and next-quarter plan." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Technical, content, backlink, and SERP audit." },
      { step: "02", title: "Topic map", desc: "Cluster and pillar strategy for topical authority." },
      { step: "03", title: "Execute", desc: "Page builds, on-page, internal linking, content." },
      { step: "04", title: "Iterate", desc: "Monthly review, refresh, and expansion." },
    ],
    features: [
      "Technical SEO audit",
      "Topical authority mapping",
      "Page and template builds",
      "Internal linking systems",
      "Content strategy & briefs",
      "Monthly reporting & roadmap",
    ],
    industries: ["SaaS", "AI Startups", "E-commerce", "Marketing Agencies"],
    faqs: [
      { q: "How long until we see results?", a: "Technical wins land in weeks. Content and topical authority compound over 3–9 months." },
      { q: "Do you write the content?", a: "We handle briefs and structure. Writing can be us, your team, or a specialist we bring in." },
      { q: "Do you do link building?", a: "We focus on earning links through content and digital PR, not paid link schemes." },
    ],
    related: {
      services: ["website-redesign", "conversion-rate-optimisation", "website-maintenance"],
      resources: ["website-seo-checklist"],
    },
  },
  {
    slug: "conversion-rate-optimisation",
    h1: "Conversion Rate Optimisation",
    metaTitle: "Conversion Rate Optimisation (CRO) Services | Devowise",
    metaDescription: "CRO services grounded in research, experimentation, and design. Move the metrics that matter, without guessing.",
    eyebrow: "CRO",
    heroTitle: "CRO backed by research, not opinions.",
    heroSub: "We combine analytics, qual research, and design to run experiments that actually move revenue.",
    overview: [
      "Most CRO programs test button colors. We build a research pipeline: analytics + session replay + user interviews feed a hypothesis backlog, which feeds prioritized experiments.",
      "Every test ships in the design system, so wins compound into the product instead of living in a one-off Optimizely variant.",
    ],
    benefits: [
      { title: "Research-first", desc: "Hypotheses grounded in real user behavior, not gut." },
      { title: "Meaningful wins", desc: "Test bigger changes with statistical rigor." },
      { title: "Design system wins", desc: "Successful tests get baked into the product." },
      { title: "Clear reporting", desc: "Impact, learnings, and next-quarter plan every month." },
    ],
    process: [
      { step: "01", title: "Research", desc: "Analytics, replay, interviews, and heuristic review." },
      { step: "02", title: "Backlog", desc: "Prioritized hypothesis list scored by impact." },
      { step: "03", title: "Experiment", desc: "Design, build, launch, and measure." },
      { step: "04", title: "Bake in", desc: "Ship winners to production, kill losers." },
    ],
    features: [
      "Analytics & event audit",
      "Session replay & user interviews",
      "Prioritized experiment backlog",
      "Design and build of variants",
      "Statistical analysis & reporting",
      "Wins baked into design system",
    ],
    industries: ["SaaS", "E-commerce", "AI Startups", "Coaches & Consultants"],
    faqs: [
      { q: "Which testing tool do you use?", a: "GrowthBook, VWO, Optimizely, or custom feature-flag based experimentation, we're tool-agnostic." },
      { q: "How many tests per month?", a: "Usually 2–4 meaningful tests per month, depending on traffic and scope." },
      { q: "Do you need high traffic?", a: "It helps. Under 20k monthly sessions we lean on qualitative research and design bets." },
    ],
    related: {
      services: ["seo-services", "landing-page-design", "website-maintenance"],
      solutions: ["website-not-converting", "improve-conversion"],
    },
  },
];