import type { ContentPage } from "./types";

export const solutions: ContentPage[] = [
  {
    slug: "website-not-converting",
    h1: "Website Not Converting?",
    metaTitle: "Website Not Converting? Diagnose & Fix It | Devowise",
    metaDescription: "If your website isn't converting, the fix is rarely 'more traffic'. Diagnose message, hierarchy, and funnel issues with a specialist team.",
    eyebrow: "Solution",
    heroTitle: "Traffic is up, revenue isn't. Let's fix that.",
    heroSub: "A structured audit and CRO program to figure out why your site isn't converting, then ship the changes that move the number.",
    overview: [
      "'Website not converting' almost always means one of three things: unclear message, weak hierarchy, or broken funnel. We diagnose which, in that order, and fix it.",
      "Every engagement starts with an analytics + session replay + qual research pass. You get a prioritized fix list before any pixels are moved.",
    ],
    benefits: [
      { title: "Diagnose before prescribing", desc: "Root cause, not 'add more testimonials'." },
      { title: "Ship changes fast", desc: "Weekly rollouts, not quarterly redesigns." },
      { title: "Measure everything", desc: "Every change tied to a metric moved." },
      { title: "Bake wins in", desc: "Successful tests become design system defaults." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Analytics, replay, funnel breakdown." },
      { step: "02", title: "Diagnose", desc: "Message, hierarchy, funnel, technical." },
      { step: "03", title: "Fix", desc: "Priority stack of changes shipped weekly." },
      { step: "04", title: "Measure", desc: "Impact tracked, wins baked in." },
    ],
    features: [
      "Full CRO audit",
      "Message and hierarchy review",
      "Session replay analysis",
      "Prioritized fix backlog",
      "Design + build of variants",
      "Impact reporting",
    ],
    faqs: [
      { q: "How fast do we see impact?", a: "First shipped changes in 2–3 weeks. Meaningful lift usually in 4–8." },
      { q: "Do we need lots of traffic?", a: "Ideally 10k+ monthly sessions. Under that we lean on qual research." },
      { q: "Do you rebuild the whole site?", a: "Rarely, usually targeted fixes first, redesign only if genuinely needed." },
    ],
    related: {
      services: ["conversion-rate-optimisation", "landing-page-design", "website-redesign"],
      solutions: ["improve-conversion"],
    },
  },
  {
    slug: "website-redesign",
    h1: "Website Redesign Services",
    metaTitle: "Website Redesign Solutions — Without SEO Loss | Devowise",
    metaDescription: "Website redesign done properly: preserve SEO, lift conversion, and modernize your stack, all in one project.",
    eyebrow: "Solution",
    heroTitle: "Redesign the site, keep the rankings.",
    heroSub: "We plan every redesign as a migration first: redirects, schema, and analytics parity before the new design ships.",
    overview: [
      "A redesign that tanks your rankings or breaks analytics is worse than no redesign. We treat SEO, analytics continuity, and content migration as first-class scope, not last-minute panic.",
      "New design and CRO layer on top, so you get a modern site and better numbers without the classic post-launch cliff.",
    ],
    benefits: [
      { title: "SEO preserved", desc: "301 map + schema parity by default." },
      { title: "Analytics continuous", desc: "GA4, GTM, and events audited pre-launch." },
      { title: "Conversion lifted", desc: "New IA and hierarchy targeted at top metrics." },
      { title: "Modern stack", desc: "Move off legacy WordPress, Wix, or old code." },
    ],
    process: [
      { step: "01", title: "Audit", desc: "SEO, analytics, and conversion baseline." },
      { step: "02", title: "Plan", desc: "Redirect map, content model, design brief." },
      { step: "03", title: "Build", desc: "New design and migration in parallel." },
      { step: "04", title: "Launch", desc: "Redirects live, week-1 monitoring." },
    ],
    features: [
      "Technical SEO audit",
      "Redirect and schema map",
      "Content model migration",
      "Bespoke redesign",
      "New build (Framer, Webflow, or code)",
      "Post-launch monitoring",
    ],
    faqs: [
      { q: "How long does it take?", a: "6–12 weeks depending on scope and content volume." },
      { q: "Will rankings drop?", a: "Not with a proper redirect and parity plan. We monitor week-1 closely." },
      { q: "Phased launch possible?", a: "Yes, by section or template to reduce risk." },
    ],
    related: {
      services: ["website-redesign", "seo-services", "website-development"],
    },
  },
  {
    slug: "slow-website-optimisation",
    h1: "Slow Website Optimisation",
    metaTitle: "Slow Website Optimisation — Core Web Vitals Fixed | Devowise",
    metaDescription: "Fix a slow website with a targeted performance program: Core Web Vitals, LCP, INP, image pipelines, and edge caching, done right.",
    eyebrow: "Solution",
    heroTitle: "A slow site is a leaky funnel. Let's plug it.",
    heroSub: "Targeted performance work to get Core Web Vitals green, LCP under 2s, and drop bounce meaningfully.",
    overview: [
      "Slow sites lose money in two ways: users bounce, and Google ranks you lower. We fix both with a targeted program grounded in real-user data, not just Lighthouse scores.",
      "The output is a measurable lift on LCP, INP, and CLS, plus a performance budget and CI monitoring so it doesn't regress.",
    ],
    benefits: [
      { title: "Real-user gains", desc: "Measured on your actual traffic, not lab tests." },
      { title: "Core Web Vitals green", desc: "LCP, INP, CLS all in the pass range." },
      { title: "Image pipeline done right", desc: "Formats, sizes, and lazy-loading tuned." },
      { title: "Doesn't regress", desc: "CI budget and monitoring to hold the line." },
    ],
    process: [
      { step: "01", title: "Measure", desc: "RUM, CrUX, and Lighthouse baseline." },
      { step: "02", title: "Diagnose", desc: "Waterfall, main-thread, and asset audit." },
      { step: "03", title: "Fix", desc: "Images, JS, fonts, and third-party scripts." },
      { step: "04", title: "Monitor", desc: "CI budget + real-user monitoring live." },
    ],
    features: [
      "RUM & CrUX baseline",
      "Image pipeline optimization",
      "Font & JS optimization",
      "Third-party audit",
      "Edge caching setup",
      "Performance budget in CI",
    ],
    faqs: [
      { q: "How much lift is realistic?", a: "Most sites we work on go from 40s+ Lighthouse to 90+ and green Core Web Vitals." },
      { q: "Do you need to rebuild the site?", a: "Rarely, targeted fixes usually suffice." },
      { q: "Which platforms?", a: "Any: Next.js, WordPress, Shopify, Webflow, Framer." },
    ],
    related: {
      services: ["website-development", "website-maintenance", "seo-services"],
    },
  },
  {
    slug: "startup-website-design",
    h1: "Startup Website Design",
    metaTitle: "Startup Website Design — Launch Fast, Look Serious | Devowise",
    metaDescription: "Startup website design and build that punches above your funding stage. Bespoke, fast, and easy for your team to iterate on.",
    eyebrow: "Solution",
    heroTitle: "A startup site that looks like Series B on a pre-seed budget.",
    heroSub: "Bespoke design and build engineered for teams that need to launch this month, not next quarter.",
    overview: [
      "Early-stage teams don't need a 40-page site. They need a sharp homepage, a compelling story, and infrastructure that supports fast iteration as the product changes.",
      "We ship focused startup sites in 2–4 weeks, on stacks your team can extend without us.",
    ],
    benefits: [
      { title: "Ships in weeks", desc: "Focused scope, senior team, no ceremony." },
      { title: "Punches above weight", desc: "Design fidelity buyers expect from a bigger team." },
      { title: "Iteration-friendly", desc: "Framer or Webflow so you own the changes." },
      { title: "Fair pricing", desc: "Sprints starting under most redesign budgets." },
    ],
    process: [
      { step: "01", title: "Story", desc: "Positioning, message, and page plan." },
      { step: "02", title: "Design", desc: "Bespoke pages, section library." },
      { step: "03", title: "Build", desc: "Framer, Webflow, or Next.js." },
      { step: "04", title: "Launch", desc: "SEO, analytics, and handoff." },
    ],
    features: [
      "Positioning workshop",
      "5–8 page bespoke design",
      "Framer / Webflow / Next.js build",
      "CMS for blog and updates",
      "SEO foundations",
      "Iteration playbook",
    ],
    faqs: [
      { q: "How much for a startup site?", a: "Sprints start around $6k. Full bespoke sites $12–25k." },
      { q: "Can you help with positioning?", a: "Yes, that's the first thing we do." },
      { q: "Do you work with pre-seed?", a: "A lot of our work is pre-seed to Series A." },
    ],
    related: {
      services: ["website-design", "website-development", "branding-services"],
      industries: ["saas", "ai-startups"],
    },
  },
  {
    slug: "mvp-design",
    h1: "MVP Design Services",
    metaTitle: "MVP Design Services — Ship the First Version Right | Devowise",
    metaDescription: "MVP design services for early-stage teams: research-backed UX, focused feature scope, and a design system that grows with you.",
    eyebrow: "Solution",
    heroTitle: "MVP design that ships and survives contact with users.",
    heroSub: "We design first versions that are focused enough to launch fast and structured enough to grow into V2.",
    overview: [
      "An MVP fails one of two ways: too much scope so it never ships, or too little structure so it collapses when users show up. We design for the middle.",
      "You get a focused product spec, hi-fi UX, and a starter design system that survives the next 12 months of iteration.",
    ],
    benefits: [
      { title: "Focused scope", desc: "Feature list ruthlessly prioritized against user jobs." },
      { title: "Ships fast", desc: "Weeks to prototype, weeks to production." },
      { title: "Survives V2", desc: "Design system that extends, not gets replaced." },
      { title: "Engineer-friendly", desc: "Figma variants and tokens ready for dev." },
    ],
    process: [
      { step: "01", title: "Scope", desc: "Job map, feature prioritization." },
      { step: "02", title: "Design", desc: "Hi-fi flows and component starter kit." },
      { step: "03", title: "Prototype", desc: "Testable flows with real users." },
      { step: "04", title: "Handoff", desc: "Dev-mode specs, tokens, engineering QA." },
    ],
    features: [
      "Job & feature mapping",
      "Hi-fi UX for core flows",
      "Starter design system",
      "Interactive prototype",
      "Engineering-ready handoff",
      "Post-launch iteration plan",
    ],
    faqs: [
      { q: "Do you build the MVP too?", a: "Yes, our engineers ship in Next.js, TanStack, or React Native." },
      { q: "Timeline?", a: "Design 3–4 weeks, build 4–8 depending on scope." },
      { q: "Cost?", a: "Design $10–20k, build varies with scope. Sprint options available." },
    ],
    related: {
      services: ["ui-ux-design", "website-development"],
      industries: ["ai-startups", "saas"],
    },
  },
  {
    slug: "improve-conversion",
    h1: "Improve Website Conversion",
    metaTitle: "Improve Website Conversion — CRO for Product-Led Sites | Devowise",
    metaDescription: "Improve your website conversion with research-backed CRO: hypotheses, experiments, and design system wins that compound.",
    eyebrow: "Solution",
    heroTitle: "Improve conversion with rigor, not gut feelings.",
    heroSub: "A research-backed CRO program that ships hypothesis-driven experiments and bakes wins into your design system.",
    overview: [
      "Real conversion lift comes from testing bigger changes with statistical rigor, not swapping button colors. We build a research pipeline that feeds a prioritized backlog every month.",
      "Winners get baked into the design system, so lift compounds instead of living in a one-off variant.",
    ],
    benefits: [
      { title: "Bigger tests", desc: "Message, offer, and layout, not just color." },
      { title: "Statistical rigor", desc: "Proper power, sample size, and analysis." },
      { title: "Design system wins", desc: "Successful variants become defaults." },
      { title: "Compounding results", desc: "Each quarter builds on the last." },
    ],
    process: [
      { step: "01", title: "Research", desc: "Analytics, replay, interviews." },
      { step: "02", title: "Backlog", desc: "Prioritized hypothesis list." },
      { step: "03", title: "Experiment", desc: "Design, build, launch, measure." },
      { step: "04", title: "Bake in", desc: "Winners to production, losers killed." },
    ],
    features: [
      "Analytics & replay audit",
      "User interviews",
      "Experiment backlog",
      "Variant design & build",
      "Statistical reporting",
      "Design system integration",
    ],
    faqs: [
      { q: "Traffic requirements?", a: "20k+ monthly sessions is ideal. Below that we lean on qual + design bets." },
      { q: "Which tools?", a: "GrowthBook, VWO, Optimizely, or custom feature flags." },
      { q: "How many tests/month?", a: "Usually 2–4 meaningful tests." },
    ],
    related: {
      services: ["conversion-rate-optimisation", "landing-page-design"],
      solutions: ["website-not-converting"],
    },
  },
  {
    slug: "build-brand-scratch",
    h1: "Build a Brand From Scratch",
    metaTitle: "Build a Brand From Scratch — Strategy, Identity, System | Devowise",
    metaDescription: "Build a new brand from scratch with a specialist team: positioning, naming, identity, and applied system in 6–8 weeks.",
    eyebrow: "Solution",
    heroTitle: "A brand built from scratch, done right the first time.",
    heroSub: "Strategy, naming, identity, and applied system in one focused engagement, so you launch with a real brand, not a placeholder.",
    overview: [
      "Building from scratch is a rare chance to get the foundations right. We treat brand strategy, identity, and applied system as one connected project, not three siloed handoffs.",
      "You end up with a name, positioning, full identity system, and applied templates ready to launch the site, deck, and social presence.",
    ],
    benefits: [
      { title: "Strategy first", desc: "Positioning done before any visual work." },
      { title: "One coherent system", desc: "Naming, identity, and application aligned." },
      { title: "Launch-ready", desc: "Site, deck, social templates included." },
      { title: "Room to grow", desc: "System designed for sub-brands and products." },
    ],
    process: [
      { step: "01", title: "Strategy", desc: "Positioning, audience, narrative." },
      { step: "02", title: "Naming", desc: "Name, screening, domain checks." },
      { step: "03", title: "Identity", desc: "Logo, type, color, motion system." },
      { step: "04", title: "Applied", desc: "Site, deck, social, guidelines." },
    ],
    features: [
      "Brand strategy",
      "Naming",
      "Full visual identity",
      "Applied guidelines",
      "Launch site",
      "Deck and social kit",
    ],
    faqs: [
      { q: "How long?", a: "6–8 weeks strategy through applied system." },
      { q: "Do you file the trademark?", a: "We screen; your counsel files." },
      { q: "Do you build the site too?", a: "Yes, included or as a follow-on sprint." },
    ],
    related: {
      services: ["branding-services", "brand-identity-design", "logo-design", "website-design"],
    },
  },
  {
    slug: "modern-website-design",
    h1: "Modern Website Design",
    metaTitle: "Modern Website Design — Editorial, Fast, and Distinctive | Devowise",
    metaDescription: "Modern website design that skips template aesthetics: bespoke layouts, motion with intent, and stacks your team can own.",
    eyebrow: "Solution",
    heroTitle: "Modern website design that doesn't look like every other Framer template.",
    heroSub: "Bespoke editorial layouts, motion with intent, and a build stack your team can extend.",
    overview: [
      "Modern doesn't mean 'trend-of-the-quarter'. We design sites that feel current now and won't look dated in 24 months, grounded in typographic craft and disciplined motion.",
      "Built in Framer, Webflow, or code depending on your team's ability to own it after launch.",
    ],
    benefits: [
      { title: "Editorial, not templated", desc: "Layouts that feel authored." },
      { title: "Motion with intent", desc: "Interactions that guide, not decorate." },
      { title: "Ages well", desc: "Craft over trend." },
      { title: "Team-friendly", desc: "Your team can iterate after launch." },
    ],
    process: [
      { step: "01", title: "Positioning", desc: "Message and page plan." },
      { step: "02", title: "Design", desc: "Bespoke pages and section library." },
      { step: "03", title: "Build", desc: "Framer, Webflow, or Next.js." },
      { step: "04", title: "Launch", desc: "SEO, analytics, and handoff." },
    ],
    features: [
      "Bespoke page design",
      "Reusable section system",
      "Motion and interaction spec",
      "Framer / Webflow / code build",
      "SEO foundations",
      "Editor training",
    ],
    faqs: [
      { q: "Framer or Webflow?", a: "Framer for motion and iteration speed; Webflow for CMS depth and enterprise governance." },
      { q: "Timeline?", a: "4–8 weeks depending on scope." },
      { q: "Cost?", a: "$12–40k range depending on pages and complexity." },
    ],
    related: {
      services: ["website-design", "framer-development", "webflow-development"],
    },
  },
  {
    slug: "mobile-responsive-website",
    h1: "Mobile Responsive Website",
    metaTitle: "Mobile Responsive Website Design & Build | Devowise",
    metaDescription: "Mobile-first responsive website design and build. Fast on real devices, accessible, and tuned for the way people actually browse.",
    eyebrow: "Solution",
    heroTitle: "Mobile-first, not mobile-afterthought.",
    heroSub: "Sites designed and built mobile-first, tested on real devices, and tuned for the way your users actually browse.",
    overview: [
      "Most sites still get designed at 1440 and shrunk. We do the opposite: design mobile first, then scale up. That means better hierarchy, faster load, and higher mobile conversion.",
      "Every build is tested on real devices, not just Chrome DevTools, with performance and accessibility baked in.",
    ],
    benefits: [
      { title: "Mobile-first hierarchy", desc: "Designed for the smallest screen first." },
      { title: "Real-device tested", desc: "iOS, Android, mid-range and flagship." },
      { title: "Fast on 4G", desc: "LCP under 2s on mid-range mobile." },
      { title: "Accessible", desc: "WCAG 2.2 AA baseline." },
    ],
    process: [
      { step: "01", title: "Content", desc: "Mobile hierarchy and message plan." },
      { step: "02", title: "Design", desc: "Mobile-first, scale up." },
      { step: "03", title: "Build", desc: "Responsive across every breakpoint." },
      { step: "04", title: "Test", desc: "Real-device QA and performance pass." },
    ],
    features: [
      "Mobile-first design",
      "Every breakpoint covered",
      "Real-device QA",
      "Performance budget",
      "Accessibility baseline",
      "Analytics setup",
    ],
    faqs: [
      { q: "Do you support tablet specifically?", a: "Yes, portrait and landscape breakpoints designed explicitly." },
      { q: "PWA?", a: "Optional add-on for installable apps." },
      { q: "Native app?", a: "Yes, React Native or Expo for a shared codebase." },
    ],
    related: {
      services: ["website-design", "website-development", "ui-ux-design"],
    },
  },
  {
    slug: "custom-business-website",
    h1: "Custom Business Website",
    metaTitle: "Custom Business Website Design & Development | Devowise",
    metaDescription: "Custom business websites built to fit your operations, not a template. Bespoke design, integrations, and a stack your team can own.",
    eyebrow: "Solution",
    heroTitle: "A custom business website that fits your operations.",
    heroSub: "Bespoke design and build tailored to how your business actually runs, not what a template thinks it should.",
    overview: [
      "Most business websites are templates dressed up in your brand colors. We build custom, from the CMS model to the integrations, so your site is a real operating surface.",
      "That means booking, quotes, portals, or specific integrations built the way your team actually uses them.",
    ],
    benefits: [
      { title: "Fits your operations", desc: "CMS, forms, and flows designed around real ops." },
      { title: "Real integrations", desc: "CRM, calendar, payments, and bespoke APIs." },
      { title: "Owned by your team", desc: "Editor training and documentation." },
      { title: "Extends over time", desc: "Design system ready for new sections and features." },
    ],
    process: [
      { step: "01", title: "Discover", desc: "Operations, integrations, and goals." },
      { step: "02", title: "Design", desc: "Bespoke pages and flows." },
      { step: "03", title: "Build", desc: "Custom CMS, integrations, forms." },
      { step: "04", title: "Launch", desc: "Training, SEO, and go-live." },
    ],
    features: [
      "Custom CMS model",
      "CRM and calendar integrations",
      "Payment and booking flows",
      "Multi-location or multi-service structure",
      "Editor training",
      "SEO and analytics",
    ],
    faqs: [
      { q: "Which stacks?", a: "Framer, Webflow, WordPress, or Next.js depending on needs." },
      { q: "Can you integrate our CRM?", a: "Yes, HubSpot, Salesforce, Pipedrive, Zoho, or bespoke." },
      { q: "Ongoing support?", a: "Yes, monthly retainer available." },
    ],
    related: {
      services: ["website-design", "website-development", "website-maintenance"],
    },
  },
];